# Generated by Django 6.0.6 on 2026-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fitimet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategoria", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("shuma", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="shpenzimet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategoria", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("shuma", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="totali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fitimet_totale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "shpenzimet_totale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gjendja", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-gjendja"],
            },
        ),
    ]
